---
# Local:
# esphome run airgradient-diy.yaml --device /dev/ttyUSB0
#
# OTA:
# esphome run airgradient-diy.yaml --device airgradient-juho
#
# Adapted from: https://github.com/m-reiner/airgradient-esphome-prometheus
esphome:
  name: !secret name
  platform: ESP8266
  board: d1_mini

logger:

api:
  encryption:
    key:
      !secret api_key

ota:
  password: !secret ota_password

# See: https://community.home-assistant.io/t/esphome-flashing-over-wifi-does-not-work/357352
switch:
  - platform: safe_mode
    name: "Flash Mode (Safe Mode)"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
# To use a static IP, uncomment this block of configuration:
#  manual_ip:
#    static_ip: PleaseChangeMe
#    gateway: PleaseChangeMe
#    subnet: 255.255.255.0

# text_sensor:
#   - platform: wifi_info
#     ip_address:
#       name: ESP IP Address
#       id: esp_ip_address

i2c:
  sda: D2
  scl: D1

font:
  - file: "gfonts://Open Sans@Regular"
    id: opensans
    size: 12
    glyphs: "!\"%()+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyzµ²³/"
  - file: "gfonts://Open Sans@Regular"
    id: opensans2
    size: 24

display:
  - platform: ssd1306_i2c
    id: oled
    address: 0x3c
    # rotation: 180°
    model: "SH1106 128x64"
    pages:
      - id: page1
        lambda: |-
          it.printf(0, 0, id(opensans), "CO2: %.0f ppm", id(co2).state);
          it.printf(0, 12, id(opensans), "PM: %.0f %0.f %0.f µg/m³", id(pm10).state, id(pm25).state, id(pm100).state);
          it.printf(0, 24, id(opensans), "VOC: %.0f", id(voc).state);
          it.printf(0, 36, id(opensans2), "%0.f°C  %.0f%%", id(temp).state, id(humidity).state);

# Provide a /metrics endpoint for Prometheus
prometheus:
web_server:
  port: 9926
  version: 1

# Set an interval to loop through the OLED screens.
interval:
  - interval: 5s
    then:
      - display.page.show_next: oled
      - component.update: oled

uart:
  - rx_pin: D5
    tx_pin: D6
    baud_rate: 9600
    id: uart1
  - rx_pin: D4
    tx_pin: D3
    baud_rate: 9600
    id: uart2

sensor:
  - platform: sht3xd
    temperature:
      id: temp
      name: "Temperature"
    humidity:
      id: humidity
      name: "Humidity"
    address: 0x44
    update_interval: 10s

  - platform: pmsx003
    # type can be PMSX003, PMS5003S, PMS5003T, PMS5003ST
    # https://esphome.io/components/sensor/pmsx003.html
    type: PMSX003
    uart_id: uart1
    pm_1_0:
      id: pm10
      name: "Particulate Matter <1.0µm Concentration"
    pm_2_5:
      id: pm25
      name: "Particulate Matter <2.5µm Concentration"
    update_interval: 60s
    pm_10_0:
      id: pm100
      name: "Particulate Matter <10.0µm Concentration"
# If you have a version of the PMS*003* sensor that supports formaldehyde, uncomment the below block
#    formaldehyde:
#      id: hcho
#      name: "Formaldehyde (HCHO) concentration in µg per cubic meter"

  - platform: senseair
    uart_id: uart2
    co2:
      id: co2
      name: "CO2 level"
    update_interval: 60s

  - platform: sgp4x
    voc:
      id: voc
      name: "VOC Index"
    nox:
      id: nox
      name: "NOx Index"
